steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west4-docker.pkg.dev/mlops-447809/artifact-registry-1-mlops/my_im',
    '-f',
    'Dockerfile.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west4-docker.pkg.dev/mlops-447809/artifact-registry-1-mlops/my_im'
  ]
options:
 logging: CLOUD_LOGGING_ONLY
